# Generated by Django 5.1.1 on 2025-03-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_gestor_th_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido', models.CharField(max_length=100, verbose_name='Título Obtenido')),
                ('institucion_educativa', models.CharField(max_length=100, verbose_name='Institución Educativa')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_culminado', models.DateField(verbose_name='Fecha de Culminado')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateField(verbose_name='Fecha de Finalizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Hoja_Vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_th.academico')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_th.experiencia_laboral')),
                ('gestor_th', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.gestor_th')),
                ('personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
            ],
        ),
    ]
