# Generated by Django 5.1.1 on 2025-03-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_aux_adm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='desconocida', max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('nivel_categorizacion', models.CharField(choices=[('I', 'Nivel I'), ('II', 'Nivel II'), ('III', 'Nivel III'), ('IV', 'Nivel IV')], max_length=100)),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Hoja_Vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('gestor_th', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.gestor_th')),
                ('personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateField(verbose_name='Fecha de Finalizacion')),
                ('tipo_contrato', models.CharField(choices=[('1', 'Contrato a término indefinido'), ('2', 'Contrato a término fijo'), ('3', 'Contrato por obra o labor'), ('4', 'Contrato ocasional, accidental o transitorio'), ('5', 'Contrato de aprendizaje'), ('6', 'Contrato de prestación de servicios'), ('7', 'Contrato sindical ')], max_length=100, verbose_name='Tipo de contrato')),
                ('hoja_vida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.hoja_vida')),
            ],
        ),
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido', models.CharField(max_length=100, verbose_name='Título Obtenido')),
                ('institucion_educativa', models.CharField(max_length=100, verbose_name='Institución Educativa')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_culminado', models.DateField(verbose_name='Fecha de Culminado')),
                ('nivel_educativo', models.CharField(choices=[('1', 'Tecnico laboral en salud'), ('2', 'Auxiliar de enfermeria'), ('3', 'Auxiliar en salud oral'), ('4', 'Auxiliar en servicios farmaceuticos'), ('5', 'Auxiliar en atencion Prehospitalaria'), ('6', 'Tecnologo en salud'), ('7', 'Tecnologia en regencia de farmacia'), ('8', 'Tecnologia en atenciaon prehospitalaria'), ('9', 'Tecnologo en laboratorio clinico'), ('10', 'medicina'), ('11', 'enfermeria'), ('12', 'odontologia'), ('13', 'Fisioterapia'), ('14', 'Terapia ocupacional'), ('15', 'Bacteriologia y laboratorio clinico')], default='Tecnologo en salud', max_length=100, verbose_name='Nivel Educativo')),
                ('hoja_vida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.hoja_vida')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=False)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.ips')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudActualizacionHV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
            ],
        ),
    ]
