# Generated by Django 5.1.6 on 2025-03-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Th', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cups',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=False)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.ips')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
