# Generated by Django 5.1.6 on 2025-04-22 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestor_Th', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoja_vida',
            name='gestor_th',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.gestor_th'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='personal_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='experiencia_laboral',
            name='hoja_vida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.hoja_vida'),
        ),
        migrations.AddField(
            model_name='academico',
            name='hoja_vida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.hoja_vida'),
        ),
        migrations.AddField(
            model_name='cups',
            name='ips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.ips'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='ips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.ips'),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionhv',
            name='personal_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
    ]
