# Generated by Django 5.1.1 on 2025-03-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Th', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ips',
            old_name='telefon',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.AddField(
            model_name='servicio',
            name='codigo',
            field=models.CharField(default='001', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
