# Generated by Django 5.1.1 on 2025-03-24 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Th', '0002_rename_telefon_ips_telefono_remove_servicio_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.ips')),
            ],
        ),
    ]
