# Generated by Django 5.1.1 on 2025-04-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Th', '0003_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
