# Generated by Django 5.1.1 on 2025-04-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Th', '0004_rename_nombre_servicio_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Cups',
        ),
    ]
