# Generated by Django 5.1.1 on 2025-04-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Th', '0002_cups_delete_servicio'),
        ('Gestor_Th', '0005_rename_servicio_cups'),
    ]

    operations = [
    ]
