# Generated by Django 5.1.6 on 2025-03-07 21:04

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_gestor_th_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de la Consulta')),
                ('inicio_sintomas', models.DateField(verbose_name='Inicio de los Sintomas')),
                ('sintomas', models.TextField(verbose_name='Sintomas')),
                ('alergias', models.CharField(max_length=50, verbose_name='Alergias')),
                ('enfermedades_base', models.CharField(max_length=100, verbose_name='Enfermedades de Base')),
                ('habitos', models.CharField(choices=[('Tabaco', 'Tabaco'), ('Alcohol', 'Alcohol'), ('Drogas', 'Drogas')], max_length=10, verbose_name='Consumo de sustancias')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupacion')),
                ('regimen', models.CharField(choices=[('RC', 'Régimen Contributivo'), ('RS', 'Régimen Subsidiado'), ('RE', 'Régimen Especial'), ('PA', 'Particular')], max_length=10)),
                ('estrato', models.CharField(choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=1, verbose_name='Estrato')),
                ('tipo_afiliacion', models.CharField(choices=[('COT', 'Cotizante'), ('BEN', 'Beneficiario'), ('ADI', 'Adicional'), ('NC', 'No Cotizante')], max_length=3, verbose_name='Tipo de Afiliación')),
                ('grupo_atencion_especial', models.CharField(choices=[('I', 'Indígena'), ('N', 'Negro'), ('D', 'Desplazado'), ('O', 'Otro')], max_length=1, verbose_name='Grupo de Atención Especial')),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo')], max_length=3, verbose_name='RH')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Diagnostico')),
                ('tipo_diagnostico', models.CharField(choices=[('Principal', 'Diagnóstico Principal'), ('Secundarios', 'Diagnósticos Secundarios'), ('Diferencial', 'Diagnóstico Diferencial'), ('Confirmado', 'Diagnóstico Confirmado'), ('Enfermedad Aguda', 'Diagnóstico de Enfermedad Aguda'), ('Rehabilitacion', 'Diagnóstico de Rehabilitación'), ('Salud Mental', 'Diagnóstico de Salud Mental'), ('Preventivo', 'Diagnóstico Preventivo'), ('Riesgo', 'Diagnóstico de Riesgo'), ('Sindrome', 'Diagnóstico de Síndrome')], max_length=20, verbose_name='Tipo de Diagnóstico')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='ExameFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Examen físico')),
                ('anamnesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(default=datetime.date.today, verbose_name='Fecha de Atención')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='historia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.historiaclinica'),
        ),
        migrations.CreateModel(
            name='OrdenDeProcedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código del procedimiento')),
                ('cups', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('cantidad', models.CharField(max_length=10, verbose_name='Cantidad')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('observacion', models.CharField(max_length=100, verbose_name='Observación')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.FloatField(verbose_name='Frecuencia Cardiaca')),
                ('prsion_arterial', models.FloatField(verbose_name='Presion Arterial')),
                ('frecuencia_respiratoria', models.FloatField(verbose_name='Frecuencia Respiratoria')),
                ('temperatura_corporal', models.FloatField(verbose_name='Temperatura Corporal')),
                ('sauracion', models.CharField(max_length=10, verbose_name='Saturación')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('talla', models.FloatField(verbose_name='Talla')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='Indice de masa Corporal')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.anamnesis')),
            ],
        ),
    ]
