# Generated by Django 5.1.6 on 2025-04-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestor_Th', '0002_cups_delete_servicio'),
        ('usuarios', '0004_gerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de la Consulta')),
                ('inicio_sintomas', models.DateField(verbose_name='Inicio de los Sintomas')),
                ('sintomas', models.TextField(verbose_name='Sintomas')),
                ('alergias', models.CharField(max_length=50, verbose_name='Alergias')),
                ('enfermedades_base', models.CharField(max_length=100, verbose_name='Enfermedades de Base')),
                ('habitos', models.CharField(choices=[('Tabaco', 'Tabaco'), ('Alcohol', 'Alcohol'), ('Drogas', 'Drogas'), ('No', 'No Aplica')], max_length=10, verbose_name='Consumo de sustancias')),
                ('examen_fisico', models.TextField(verbose_name='Examen Físico')),
            ],
        ),
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cie10', models.CharField(max_length=15, verbose_name='Código dde la enfermedad')),
                ('nombre_cie10', models.TextField(verbose_name='Nombre de la enfermedad')),
                ('descripcion_cie10', models.TextField(verbose_name='Descripcion de la enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=100, verbose_name='Nombre del Medicamento')),
                ('concentracion', models.CharField(max_length=50, verbose_name='Concentracion del Medicamento')),
                ('forma_farmaceutica', models.CharField(max_length=50, verbose_name='Forma Farmaceútica del Medicamento')),
                ('dosis', models.CharField(max_length=50, verbose_name='Dosis')),
                ('via_administracion', models.CharField(choices=[('VO', 'Vía oral'), ('VR', 'Vía rectal'), ('VT', 'Vía tópica'), ('TD', 'Vía transdérmica '), ('VI', 'Vía inhalatoria '), ('IV', 'Vía intravenosa'), ('IM', 'Vía intramuscular'), ('SC', 'Vía subcutánea'), ('IO', 'Vía intraósea'), ('IT', 'Vía intratecal'), ('SL', 'Vía sublingual')], max_length=2, verbose_name='Vía de Administración')),
                ('frecuencia', models.CharField(max_length=20, verbose_name='Frecuencia del Medicamento')),
                ('tiempo_tratamiento', models.CharField(max_length=30, verbose_name='Tiempo del Tratamiento')),
                ('cantidad', models.CharField(max_length=10, verbose_name='Cantidad del Medicamento')),
                ('cantidad_letras', models.CharField(max_length=50, verbose_name='Cantidad en letras')),
                ('posologia', models.CharField(max_length=100, verbose_name='Posología')),
                ('recomendaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recomendaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Paraclinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados', models.TextField(verbose_name='Resultados de los examenes')),
                ('analisis', models.TextField(verbose_name='Análisis de los resultados')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.FloatField(verbose_name='Frecuencia Cardiaca')),
                ('presion_arterial', models.FloatField(verbose_name='Presion Arterial')),
                ('frecuencia_respiratoria', models.FloatField(verbose_name='Frecuencia Respiratoria')),
                ('temperatura_corporal', models.FloatField(verbose_name='Temperatura Corporal')),
                ('saturacion', models.CharField(max_length=10, verbose_name='Saturación')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('talla', models.FloatField(verbose_name='Talla')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='Indice de masa Corporal')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diagnostico', models.CharField(choices=[('Principal', 'Diagnóstico Principal'), ('Secundarios', 'Diagnósticos Secundarios'), ('Diferencial', 'Diagnóstico Diferencial'), ('Confirmado', 'Diagnóstico Confirmado'), ('Enfermedad Aguda', 'Diagnóstico de Enfermedad Aguda'), ('Rehabilitacion', 'Diagnóstico de Rehabilitación'), ('Salud Mental', 'Diagnóstico de Salud Mental'), ('Preventivo', 'Diagnóstico Preventivo'), ('Riesgo', 'Diagnóstico de Riesgo'), ('Sindrome', 'Diagnóstico de Síndrome')], max_length=20, verbose_name='Tipo de Diagnóstico')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Diagnostico')),
                ('cie10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.cie10', verbose_name='Código de la enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diagnostico', models.CharField(choices=[('Principal', 'Diagnóstico Principal'), ('Secundarios', 'Diagnósticos Secundarios'), ('Diferencial', 'Diagnóstico Diferencial'), ('Confirmado', 'Diagnóstico Confirmado'), ('Enfermedad Aguda', 'Diagnóstico de Enfermedad Aguda'), ('Rehabilitacion', 'Diagnóstico de Rehabilitación'), ('Salud Mental', 'Diagnóstico de Salud Mental'), ('Preventivo', 'Diagnóstico Preventivo'), ('Riesgo', 'Diagnóstico de Riesgo'), ('Sindrome', 'Diagnóstico de Síndrome')], max_length=20, verbose_name='Tipo de Diagnóstico')),
                ('fecha_diagnostico', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('cie10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.cie10', verbose_name='Cie10')),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateField(auto_now_add=True)),
                ('plan_de_manejo', models.TextField(verbose_name='Plan de Manejo')),
                ('evolucion', models.TextField()),
                ('recomendaciones', models.CharField(max_length=200, verbose_name='Recomendaciones')),
                ('interconsultas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Interconsultas')),
                ('plan_de_seguimiento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Plan de Seguimiento')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.diagnostico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prescripcion', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.diagnostico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeProcedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código del procedimiento')),
                ('descripcion', models.TextField(null=True)),
                ('cantidad', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('RT', 'Rutinario'), ('UR', 'Urgente'), ('EM', 'Emergencia'), ('PD', 'Pendiente'), ('EP', 'En Proceso'), ('PG', 'Programado'), ('CP', 'Completado'), ('RA', 'Requiere Autorizacion'), ('NR', 'No Realizado'), ('SP', 'Suspendido'), ('DR', 'Derivado')], max_length=2, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('cups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.cups')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_historia', models.CharField(max_length=15, verbose_name='Numero de historia')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('Nro_folio', models.PositiveIntegerField(blank=True, null=True)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.anamnesis')),
                ('antecedentes_medicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.antecedentesmedicos')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.diagnostico')),
                ('evolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.evolucion')),
                ('formula_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.formulamedica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
                ('orden_de_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='Historia_Clinica.ordendeprocedimientos')),
                ('paraclinicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.paraclinicos')),
                ('signos_vitales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.signosvitales')),
            ],
        ),
    ]
