# Generated by Django 5.1.6 on 2025-03-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0001_initial'),
        ('usuarios', '0006_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente'),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
