# Generated by Django 5.1.6 on 2025-04-22 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestor_Th', '0002_initial'),
        ('Historia_Clinica', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='formulamedica',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.diagnostico'),
        ),
        migrations.AddField(
            model_name='formulamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.anamnesis'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_medicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.antecedentesmedicos'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.diagnostico'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='evolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.evolucion'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='formula_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.formulamedica'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='formulamedica',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.medicamento'),
        ),
        migrations.AddField(
            model_name='ordendeprocedimientos',
            name='cups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Th.cups'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='orden_de_procedimientos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='Historia_Clinica.ordendeprocedimientos'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paraclinicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.paraclinicos'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='signos_vitales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.signosvitales'),
        ),
    ]
