# Generated by Django 4.2.6 on 2025-03-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='contrato',
            field=models.CharField(max_length=100, null=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(max_length=100, null=True, verbose_name='Especialidad'),
        ),
    ]
