# Generated by Django 5.1.6 on 2025-03-12 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_medico_contrato_alter_medico_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aux_adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('1', 'Contrato a término indefinido'), ('2', 'Contrato a término fijo'), ('3', 'Contrato por obra o labor'), ('4', 'Contrato ocasional, accidental o transitorio'), ('5', 'Contrato de aprendizaje'), ('6', 'Contrato de prestación de servicios'), ('7', 'Contrato sindical ')], default='hola', max_length=100, verbose_name='Tipo de contrato')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
