# Generated by Django 5.1.1 on 2025-03-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor_TH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('area_responsable', models.CharField(max_length=100, verbose_name='Área responsable')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('contrato', models.CharField(max_length=100, verbose_name='Contrato')),
                ('sueldo', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Sueldo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
