# Generated by Django 5.1.6 on 2025-03-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_gestor_th_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor_th',
            name='tipo_contrato',
            field=models.CharField(choices=[('1', 'Contrato a término indefinido'), ('2', 'Contrato a término fijo'), ('3', 'Contrato por obra o labor'), ('4', 'Contrato ocasional, accidental o transitorio'), ('5', 'Contrato de aprendizaje'), ('6', 'Contrato de prestación de servicios'), ('7', 'Contrato sindical ')], default='hola', max_length=100, verbose_name='Tipo de contrato'),
        ),
    ]
