# Generated by Django 5.1.1 on 2025-03-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(default='diosito', max_length=50),
        ),
    ]
