# Generated by Django 5.1.6 on 2025-03-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
