# Generated by Django 5.1.1 on 2025-03-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Th', '0003_cargo'),
        ('usuarios', '0006_remove_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestor_Th.cargo'),
        ),
    ]
