# Generated by Django 5.1.1 on 2025-03-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_medico_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
